### ISSUE TITLE
Make available on PyPI

### ISSUE THREAD

**Issue by Jaza** [klokantech/flask-mailgun#3]
It would be good to make this project available on PyPI. In my opinion, it's the most current and the most complete flask-mailgun implementation available at the moment.

I see that https://pypi.python.org/pypi/Flask-Mailgun is taken by https://github.com/sleekslush/flask-mailgun . I suggest that a request be made to switch that PyPI package to instead point to https://github.com/klokantech/flask-mailgun . This will require liaising with @sleekslush and with the PyPI admins.

@keosak would you be interested in making this happen?

**Comment by keosak** [comment]
As I mentioned before, this code was written to be used by my company. We are not very interested in publishing to PyPI at this moment. Note that you can still install the package over HTTPs, in fact that's what we are doing.

```shell
$ pip install https://github.com/klokantech/flask-mailgun/archive/v1.4.zip
```
